name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: curl, mbstring, xml, json
        
    - name: Validate Markdown files
      run: |
        npm install -g markdownlint-cli
        markdownlint '**/*.md' 